[[pages]]
path = "main.py"
name = "Accueil"
icon = "ğŸ "

[[pages]]
path = "pages/carte_sociosarah.py"
name = "Carte Socio Sarah"
icon = "ğŸ—ºï¸"

[[pages]]
path = "pages/quietesvous.py"
name = "Qui Ãªtes-vous ?"
icon = "ğŸ‘¤"

[[pages]]
path = "pages/top10_pokemon.py"
name = "Top 10 PokÃ©mon"
icon = "ğŸ”"
